/**
 * Utilities for managing custom presets (color + brightness)
 * Now uses backend API instead of localStorage
 */

import type { WLEDColor } from "../types/wled";
import { presetsApi, type Preset } from "../api/backendClient";

/**
 * Custom preset interface matching the frontend types
 */
export interface CustomPreset {
  id: string; // String ID for frontend compatibility
  name: string;
  color: WLEDColor;
  brightness: number;
  createdAt: number;
  deviceId?: number;
}

/**
 * Converts backend Preset to frontend CustomPreset format
 */
function backendPresetToCustomPreset(preset: Preset): CustomPreset {
  return {
    id: preset.id.toString(), // Convert number ID to string for frontend
    name: preset.name,
    color: preset.color,
    brightness: preset.brightness,
    createdAt: new Date(preset.createdAt).getTime(),
    deviceId: preset.deviceId || undefined,
  };
}

/**
 * Gets all saved presets from the API
 * Falls back to localStorage for backward compatibility during migration
 * @param deviceId - Optional device ID to filter presets
 * @returns Array of custom presets
 */
export async function getPresets(deviceId?: number): Promise<CustomPreset[]> {
  try {
    const presets = await presetsApi.getAll(deviceId ? { deviceId } : undefined);
    return presets.map(backendPresetToCustomPreset);
  } catch (error) {
    console.error("Error fetching presets from API, falling back to localStorage:", error);
    // Fallback to localStorage for backward compatibility
    return getPresetsFromLocalStorage();
  }
}

/**
 * Fallback: Gets presets from localStorage (for migration)
 */
function getPresetsFromLocalStorage(): CustomPreset[] {
  try {
    const stored = localStorage.getItem("wled_custom_presets");
    if (!stored) return [];

    const presets = JSON.parse(stored) as CustomPreset[];
    // Validate structure and fix invalid brightness values
    return presets
      .filter(
        (preset) =>
          preset.id &&
          preset.name &&
          Array.isArray(preset.color) &&
          preset.color.length === 4
      )
      .map((preset) => {
        // Ensure brightness is a valid number between 1-255
        let validBrightness = preset.brightness;
        if (
          typeof validBrightness !== "number" ||
          isNaN(validBrightness) ||
          validBrightness < 1 ||
          validBrightness > 255
        ) {
          validBrightness = 127; // Default to 127 if invalid
        }
        return {
          ...preset,
          brightness: validBrightness,
        };
      });
  } catch (error) {
    console.error("Error reading presets from localStorage:", error);
    return [];
  }
}

/**
 * Saves a preset to the API
 * @param preset - Preset to save (id will be generated by backend if not provided)
 * @returns The saved preset with id
 */
export async function savePreset(
  preset: Omit<CustomPreset, "id" | "createdAt">
): Promise<CustomPreset> {
  try {
    const createdPreset = await presetsApi.create({
      name: preset.name,
      color: preset.color,
      brightness: preset.brightness,
      deviceId: preset.deviceId,
    });

    return backendPresetToCustomPreset(createdPreset);
  } catch (error) {
    console.error("Error saving preset to API, falling back to localStorage:", error);
    // Fallback to localStorage
    return savePresetToLocalStorage(preset);
  }
}

/**
 * Fallback: Saves preset to localStorage (for migration)
 */
function savePresetToLocalStorage(
  preset: Omit<CustomPreset, "id" | "createdAt">
): CustomPreset {
  try {
    const presets = getPresetsFromLocalStorage();
    const newPreset: CustomPreset = {
      ...preset,
      id: preset.name.toLowerCase().replace(/\s+/g, "-") + "-" + Date.now(),
      createdAt: Date.now(),
    };

    presets.push(newPreset);
    localStorage.setItem("wled_custom_presets", JSON.stringify(presets));
    return newPreset;
  } catch (error) {
    console.error("Error saving preset to localStorage:", error);
    throw error;
  }
}

/**
 * Deletes a preset by ID
 * @param id - Preset ID to delete (can be string from frontend or number from backend)
 * @returns true if deleted, false if not found
 */
export async function deletePreset(id: string | number): Promise<boolean> {
  try {
    const presetId = typeof id === "string" ? parseInt(id, 10) : id;
    if (isNaN(presetId)) {
      console.error("Invalid preset ID:", id);
      return false;
    }

    await presetsApi.delete(presetId);
    return true;
  } catch (error) {
    console.error("Error deleting preset from API, trying localStorage:", error);
    // Fallback to localStorage
    return deletePresetFromLocalStorage(id.toString());
  }
}

/**
 * Fallback: Deletes preset from localStorage (for migration)
 */
function deletePresetFromLocalStorage(id: string): boolean {
  try {
    const presets = getPresetsFromLocalStorage();
    const filtered = presets.filter((p) => p.id !== id);

    if (filtered.length === presets.length) {
      console.warn("Preset not found for deletion:", id);
      return false;
    }

    localStorage.setItem("wled_custom_presets", JSON.stringify(filtered));
    return true;
  } catch (error) {
    console.error("Error deleting preset from localStorage:", error);
    return false;
  }
}

/**
 * Updates an existing preset
 * @param id - Preset ID to update (can be string from frontend or number from backend)
 * @param updates - Partial preset data to update
 * @returns Updated preset or null if not found
 */
export async function updatePreset(
  id: string | number,
  updates: Partial<Omit<CustomPreset, "id" | "createdAt">>
): Promise<CustomPreset | null> {
  try {
    const presetId = typeof id === "string" ? parseInt(id, 10) : id;
    if (isNaN(presetId)) {
      console.error("Invalid preset ID:", id);
      return null;
    }

    const updateData: {
      name?: string;
      color?: [number, number, number, number];
      brightness?: number;
      deviceId?: number | null;
    } = {};

    if (updates.name !== undefined) updateData.name = updates.name;
    if (updates.color !== undefined) updateData.color = updates.color;
    if (updates.brightness !== undefined) updateData.brightness = updates.brightness;
    if (updates.deviceId !== undefined) updateData.deviceId = updates.deviceId || null;

    const updatedPreset = await presetsApi.update(presetId, updateData);
    return backendPresetToCustomPreset(updatedPreset);
  } catch (error) {
    console.error("Error updating preset in API, trying localStorage:", error);
    // Fallback to localStorage
    return updatePresetInLocalStorage(id.toString(), updates);
  }
}

/**
 * Fallback: Updates preset in localStorage (for migration)
 */
function updatePresetInLocalStorage(
  id: string,
  updates: Partial<Omit<CustomPreset, "id" | "createdAt">>
): CustomPreset | null {
  try {
    const presets = getPresetsFromLocalStorage();
    const index = presets.findIndex((p) => p.id === id);

    if (index === -1) {
      return null;
    }

    presets[index] = {
      ...presets[index],
      ...updates,
    };

    localStorage.setItem("wled_custom_presets", JSON.stringify(presets));
    return presets[index];
  } catch (error) {
    console.error("Error updating preset in localStorage:", error);
    return null;
  }
}
